GET http://127.0.0.1:3000/cats
Accept: application/json

###
POST http://127.0.0.1:3000
Content-Type: application/json

{
  "groupName": "그룹명",
  "members": [
    "회원1",
    "회원2",
    "회원3"
  ],
  "date": {
    "year": 2018,
    "month": 1,
    "day": 24
  }
}
